=== CarloMicieli/trenako/crates/tools/cli/src/schemas/catalog-items.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CatalogItem",
  "type": "object",
  "required": [
    "manufacturer",
    "item_number",
    "scale",
    "category",
    "description",
    "power_method",
    "epoch",
    "count"
  ],
  "properties": {
    "manufacturer": {
      "type": "string",
      "minLength": 3,
      "maxLength": 50
    },
    "item_number": {
      "type": "string",
      "minLength": 1,
      "maxLength": 25
    },
    "scale": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "category": {
      "type": "string",
      "enum": [
        "ELECTRIC_MULTIPLE_UNITS",
        "FREIGHT_CARS",
        "LOCOMOTIVES",
        "PASSENGER_CARS",
        "RAILCARS",
        "STARTER_SETS",
        "TRAIN_SETS"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "power_method": {
      "type": "string",
      "enum": [
        "AC",
        "DC",
        "TRIX_EXPRESS"
      ]
    },
    "epoch": {
      "type": "string",
      "minLength": 1,
      "maxLength": 10
    },
    "delivery_date": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 4,
      "maxLength": 7
    },
    "availability_status": {
      "type": "string",
      "enum": [
        "ANNOUNCED",
        "AVAILABLE",
        "DISCONTINUED"
      ]
    },
    "rolling_stocks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RollingStock"
      }
    },
    "count": {
      "type": "integer",
      "format": "uint8",
      "minimum": 1,
      "maximum": 99
    }
  },
  "definitions": {
    "Coupling": {
      "type": "object",
      "properties": {
        "socket": {
          "type": ["string", "null"],
          "enum": [
            null,
            "NONE",
            "NEM_355",
            "NEM_356",
            "NEM_357",
            "NEM_359",
            "NEM_360",
            "NEM_362",
            "NEM_365"
          ]
        },
        "close_couplers": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "digital_shunting": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    },
    "ElectricMultipleUnitType": {
      "type": "string",
      "enum": [
        "DRIVING_CAR",
        "HIGH_SPEED_TRAIN",
        "MOTOR_CAR",
        "POWER_CAR",
        "TRAILER_CAR",
        "TRAIN_SET"
      ]
    },
    "FreightCarType": {
      "type": ["string", "null"],
      "enum": [
        null,
        "AUTO_TRANSPORT_CARS",
        "BRAKE_WAGON",
        "CONTAINER_CARS",
        "COVERED_FREIGHT_CARS",
        "DEEP_WELL_FLAT_CARS",
        "DUMP_CARS",
        "GONDOLA",
        "HEAVY_GOODS_WAGONS",
        "HINGED_COVER_WAGONS",
        "HOPPER_WAGON",
        "REFRIGERATOR_CARS",
        "SILO_CONTAINER_CARS",
        "SLIDE_TARPAULIN_WAGON",
        "SLIDING_WALL_BOXCARS",
        "SPECIAL_TRANSPORT",
        "STAKE_WAGONS",
        "SWING_ROOF_WAGON",
        "TANK_CARS",
        "TELESCOPE_HOOD_WAGONS"
      ]
    },
    "LocomotiveType": {
      "type": "string",
      "enum": [
        "DIESEL_LOCOMOTIVE",
        "ELECTRIC_LOCOMOTIVE",
        "STEAM_LOCOMOTIVE"
      ]
    },
    "PassengerCarType": {
      "type": ["string", "null"],
      "enum": [
        null,
        "BAGGAGE_CAR",
        "COMBINE_CAR",
        "COMPARTMENT_COACH",
        "DINING_CAR",
        "DOUBLE_DECKER",
        "DRIVING_TRAILER",
        "LOUNGE",
        "OBSERVATION",
        "OPEN_COACH",
        "RAILWAY_POST_OFFICE",
        "SLEEPING_CAR"
      ]
    },
    "FeatureFlag": {
      "type": "string",
      "enum": [
        "YES",
        "NO",
        "NOT_APPLICABLE"
      ]
    },
    "RailcarType": {
      "type": "string",
      "enum": [
        "null",
        "POWER_CAR",
        "TRAILER_CAR"
      ]
    },
    "RollingStock": {
      "type": "object",
      "required": [
        "category",
        "railway",
        "technical_specifications"
      ],
      "properties": {
        "category": {
          "type": "string",
          "enum": [
            "ELECTRIC_MULTIPLE_UNITS",
            "FREIGHT_CARS",
            "LOCOMOTIVES",
            "PASSENGER_CARS",
            "RAILCARS"
          ]
        },
        "control": {
          "type": ["string", "null"],
          "enum": [
            null,
            "DCC",
            "DCC_READY",
            "DCC_SOUND",
            "NO_DCC"
          ]
        },
        "dcc_interface": {
          "type": ["string", "null"],
          "enum": [
            null,
            "MTC_21",
            "NEM_651",
            "NEM_652",
            "NEM_654",
            "NEXT_18",
            "NEXT_18_S",
            "PLUX_12",
            "PLUX_16",
            "PLUX_22",
            "PLUX_8"
          ]
        },
        "depot": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100
        },
        "is_dummy": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "livery": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 50
        },
        "railway": {
          "type": "string"
        },
        "type_name": {
          "type": "string",
          "minLength": 3,
          "maxLength": 25
        },
        "road_number": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 25
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100
        },
        "service_level": {
          "type": ["string", "null"],
          "enum": [
            null,
            "FIRST_CLASS",
            "SECOND_CLASS",
            "THIRD_CLASS",
            "FIRST_AND_SECOND_CLASS",
            "FIRST_SECOND_AND_THIRD_CLASS",
            "SECOND_AND_THIRD_CLASS"
          ]
        },
        "sub_category": {
          "type": [
            "string",
            "null"
          ]
        },
        "technical_specifications": {
          "$ref": "#/definitions/TechnicalSpecifications"
        }
      }
    },
    "TechnicalSpecifications": {
      "type": "object",
      "required": [
        "body_shell",
        "chassis",
        "coupling",
        "flywheel_fitted",
        "interior_lights",
        "lights",
        "minimum_radius",
        "sprung_buffers"
      ],
      "properties": {
        "body_shell": {
          "type": ["string", "null"],
          "enum": [
            null,
            "METAL_DIE_CAST",
            "PLASTIC"
          ]
        },
        "chassis": {
          "type": ["string", "null"],
          "enum": [
            null,
            "METAL_DIE_CAST",
            "PLASTIC"
          ]
        },
        "coupling": {
          "$ref": "#/definitions/Coupling"
        },
        "flywheel_fitted": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "interior_lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "minimum_radius": {
          "type": ["number", "null"],
          "minimum": 0.1
        },
        "sprung_buffers": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    }
  }
}

=== CarloMicieli/trenako/dataset/catalog_items/piko/locomotives/97471.json
{
  "manufacturer": "Piko",
  "item_number": "97471",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva elettrica E.428 FS di prima serie con prese d'aria basse"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2024",
  "availability_status": "ANNOUNCED",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E428",
      "road_number": "E428 ???",
      "series": "prima serie con avancorpi",
      "livery": "castano/Isabella",
      "length_over_buffers": {
        "inches": null,
        "millimeters": 218.0
      },
      "technical_specifications": {
        "minimum_radius": 358.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": "PLASTIC",
        "chassis": "METAL_DIE_CAST",
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_SOUND",
      "dcc_interface": "PLUX_22",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/rivarossi-hornby/electric_multiple_units/HR2964S.json
{
  "manufacturer": "Rivarossi/Hornby",
  "item_number": "HR2964S",
  "scale": "H0",
  "category": "ELECTRIC_MULTIPLE_UNITS",
  "power_method": "DC",
  "epoch": "V",
  "description": {
    "de": null,
    "fr": null,
    "en": "SBB, tilting high-speed train type ETR 470 silver livery with blue stripe, 4-unit base set, ep. V",
    "it": "FFS, set di 4 unità, treno ad alta velocità ad assetto variabile ETR 470, livrea argento con strisce blu, ep. V"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2024",
  "availability_status": "ANNOUNCED",
  "rolling_stocks": [
    {
      "category": "ELECTRIC_MULTIPLE_UNITS",
      "electric_multiple_unit_type": "TRAIN_SET",
      "railway": "SBB",
      "class_name": "Etr 470",
      "road_number": "Etr 470 ???",
      "livery": "livrea argento con strisce blu",
      "length_over_buffers": {
        "inches": null,
        "millimeters": 1228.0
      },
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "YES",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_SOUND",
      "dcc_interface": "MTC_21",
      "is_dummy": false
    }
  ],
  "count": 4
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/69503.json
{
  "manufacturer": "ACME",
  "item_number": "69503",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Fanali elettrici, carboniera alta, respingenti moderni, ruotino a vela piena, DCC Sound"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2012",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "STEAM_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "685",
      "road_number": "685 157",
      "series": "TERZA SERIE",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/rivarossi-hornby/locomotives/HR2643.json
{
  "manufacturer": "Rivarossi/Hornby",
  "item_number": "HR2643",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "VI",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Livrea “Frecciabianca” bianco/grigio scuro fasce rosse, scritta grande, antenne, captatori"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2016",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E402 B",
      "road_number": "E402 128",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/60446.json
{
  "manufacturer": "ACME",
  "item_number": "60446",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "V",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotive elettrica FS E636 287 nella livrea isabella, pantografi 52 strisciante piatto, aria condizionata, dep. Roma S.L."
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2014",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E636",
      "road_number": "E636 287",
      "series": "TERZA SERIE",
      "depot": "Roma San Lorenzo",
      "livery": "isabella",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "dcc_interface": "MTC_21",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/rivarossi-hornby/locomotives/HR2176.json
{
  "manufacturer": "Rivarossi/Hornby",
  "item_number": "HR2176",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva elettrica E428 102 con compressore meccanico, separatore D'Arbela, DCC Sound"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2011",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E428",
      "road_number": "E428 102",
      "series": "seconda serie con avancorpi",
      "livery": "castano/isabella",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "YES"
      },
      "control": "DCC_SOUND",
      "dcc_interface": "NEM_652",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/roco/locomotives/43614.2 (1).json
{
  "manufacturer": "Roco",
  "item_number": "43614.2 (1)",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "IV",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Verde/isabella, vetri tondi, costruzione Fiat Ferr. Savigliano, deposito Benevento"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "1992",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "DIESEL_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "D345",
      "road_number": "D345 1092",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/rivarossi-hornby/passenger_cars/HR4367.json
{
  "manufacturer": "Rivarossi/Hornby",
  "item_number": "HR4367",
  "scale": "H0",
  "category": "PASSENGER_CARS",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": "FS, 2-unit pack of coaches, Castano/Isabella livery, including 1 x 2nd class coach Bz 33010 Type 1946 with “ristoro” compartment and 1 x 2nd class coach Bz 33010, ep. II",
    "it": "FS, set di 2 carrozze Tipo 1946, composto da 2 carrozze di 2a classe Bz 33010, una con comparto ristoro, livrea castano/Isabella, ep. III"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2024",
  "availability_status": "ANNOUNCED",
  "rolling_stocks": [
    {
      "category": "PASSENGER_CARS",
      "railway": "FS",
      "type_name": "Tipo 46",
      "livery": "castano/Isabella",
      "service_level": "SECOND_CLASS",
      "length_over_buffers": {
        "inches": null,
        "millimeters": 262.0
      },
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NOT_APPLICABLE",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "NO",
        "sprung_buffers": "YES"
      },
      "is_dummy": null
    },
    {
      "category": "PASSENGER_CARS",
      "railway": "FS",
      "type_name": "Tipo 46",
      "livery": "castano/Isabella",
      "service_level": "SECOND_CLASS",
      "length_over_buffers": {
        "inches": null,
        "millimeters": 262.0
      },
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NOT_APPLICABLE",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "NO",
        "sprung_buffers": "YES"
      },
      "is_dummy": null
    }
  ],
  "count": 2
}
