=== CarloMicieli/trenako/crates/tools/cli/src/schemas/catalog-items.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CatalogItem",
  "type": "object",
  "required": [
    "manufacturer",
    "item_number",
    "scale",
    "category",
    "description",
    "power_method",
    "epoch",
    "count"
  ],
  "properties": {
    "manufacturer": {
      "type": "string",
      "minLength": 3,
      "maxLength": 50
    },
    "item_number": {
      "type": "string",
      "minLength": 1,
      "maxLength": 25
    },
    "scale": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "category": {
      "type": "string",
      "enum": [
        "ELECTRIC_MULTIPLE_UNITS",
        "FREIGHT_CARS",
        "LOCOMOTIVES",
        "PASSENGER_CARS",
        "RAILCARS",
        "STARTER_SETS",
        "TRAIN_SETS"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "power_method": {
      "type": "string",
      "enum": [
        "AC",
        "DC",
        "TRIX_EXPRESS"
      ]
    },
    "epoch": {
      "type": "string",
      "minLength": 1,
      "maxLength": 10
    },
    "delivery_date": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 4,
      "maxLength": 7
    },
    "availability_status": {
      "type": "string",
      "enum": [
        "ANNOUNCED",
        "AVAILABLE",
        "DISCONTINUED"
      ]
    },
    "rolling_stocks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RollingStock"
      }
    },
    "count": {
      "type": "integer",
      "format": "uint8",
      "minimum": 1,
      "maximum": 99
    }
  },
  "definitions": {
    "Coupling": {
      "type": "object",
      "properties": {
        "socket": {
          "type": ["string", "null"],
          "enum": [
            null,
            "NONE",
            "NEM_355",
            "NEM_356",
            "NEM_357",
            "NEM_359",
            "NEM_360",
            "NEM_362",
            "NEM_365"
          ]
        },
        "close_couplers": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "digital_shunting": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    },
    "ElectricMultipleUnitType": {
      "type": "string",
      "enum": [
        "DRIVING_CAR",
        "HIGH_SPEED_TRAIN",
        "MOTOR_CAR",
        "POWER_CAR",
        "TRAILER_CAR",
        "TRAIN_SET"
      ]
    },
    "FreightCarType": {
      "type": ["string", "null"],
      "enum": [
        null,
        "AUTO_TRANSPORT_CARS",
        "BRAKE_WAGON",
        "CONTAINER_CARS",
        "COVERED_FREIGHT_CARS",
        "DEEP_WELL_FLAT_CARS",
        "DUMP_CARS",
        "GONDOLA",
        "HEAVY_GOODS_WAGONS",
        "HINGED_COVER_WAGONS",
        "HOPPER_WAGON",
        "REFRIGERATOR_CARS",
        "SILO_CONTAINER_CARS",
        "SLIDE_TARPAULIN_WAGON",
        "SLIDING_WALL_BOXCARS",
        "SPECIAL_TRANSPORT",
        "STAKE_WAGONS",
        "SWING_ROOF_WAGON",
        "TANK_CARS",
        "TELESCOPE_HOOD_WAGONS"
      ]
    },
    "LocomotiveType": {
      "type": "string",
      "enum": [
        "DIESEL_LOCOMOTIVE",
        "ELECTRIC_LOCOMOTIVE",
        "STEAM_LOCOMOTIVE"
      ]
    },
    "PassengerCarType": {
      "type": ["string", "null"],
      "enum": [
        null,
        "BAGGAGE_CAR",
        "COMBINE_CAR",
        "COMPARTMENT_COACH",
        "DINING_CAR",
        "DOUBLE_DECKER",
        "DRIVING_TRAILER",
        "LOUNGE",
        "OBSERVATION",
        "OPEN_COACH",
        "RAILWAY_POST_OFFICE",
        "SLEEPING_CAR"
      ]
    },
    "FeatureFlag": {
      "type": "string",
      "enum": [
        "YES",
        "NO",
        "NOT_APPLICABLE"
      ]
    },
    "RailcarType": {
      "type": "string",
      "enum": [
        "null",
        "POWER_CAR",
        "TRAILER_CAR"
      ]
    },
    "RollingStock": {
      "type": "object",
      "required": [
        "category",
        "railway",
        "technical_specifications"
      ],
      "properties": {
        "category": {
          "type": "string",
          "enum": [
            "ELECTRIC_MULTIPLE_UNITS",
            "FREIGHT_CARS",
            "LOCOMOTIVES",
            "PASSENGER_CARS",
            "RAILCARS"
          ]
        },
        "control": {
          "type": ["string", "null"],
          "enum": [
            null,
            "DCC",
            "DCC_READY",
            "DCC_SOUND",
            "NO_DCC"
          ]
        },
        "dcc_interface": {
          "type": ["string", "null"],
          "enum": [
            null,
            "MTC_21",
            "NEM_651",
            "NEM_652",
            "NEM_654",
            "NEXT_18",
            "NEXT_18_S",
            "PLUX_12",
            "PLUX_16",
            "PLUX_22",
            "PLUX_8"
          ]
        },
        "depot": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100
        },
        "is_dummy": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "livery": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 50
        },
        "railway": {
          "type": "string"
        },
        "type_name": {
          "type": "string",
          "minLength": 3,
          "maxLength": 25
        },
        "road_number": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 25
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100
        },
        "service_level": {
          "type": ["string", "null"],
          "enum": [
            null,
            "FIRST_CLASS",
            "SECOND_CLASS",
            "THIRD_CLASS",
            "FIRST_AND_SECOND_CLASS",
            "FIRST_SECOND_AND_THIRD_CLASS",
            "SECOND_AND_THIRD_CLASS"
          ]
        },
        "sub_category": {
          "type": [
            "string",
            "null"
          ]
        },
        "technical_specifications": {
          "$ref": "#/definitions/TechnicalSpecifications"
        }
      }
    },
    "TechnicalSpecifications": {
      "type": "object",
      "required": [
        "body_shell",
        "chassis",
        "coupling",
        "flywheel_fitted",
        "interior_lights",
        "lights",
        "minimum_radius",
        "sprung_buffers"
      ],
      "properties": {
        "body_shell": {
          "type": ["string", "null"],
          "enum": [
            null,
            "METAL_DIE_CAST",
            "PLASTIC"
          ]
        },
        "chassis": {
          "type": ["string", "null"],
          "enum": [
            null,
            "METAL_DIE_CAST",
            "PLASTIC"
          ]
        },
        "coupling": {
          "$ref": "#/definitions/Coupling"
        },
        "flywheel_fitted": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "interior_lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "minimum_radius": {
          "type": ["number", "null"],
          "minimum": 0.1
        },
        "sprung_buffers": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    }
  }
}

=== CarloMicieli/trenako/dataset/catalog_items/lima/locomotives/208227.json
{
  "manufacturer": "Lima",
  "item_number": "208227",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Castano/isabella/rosso, 2 fanali, corrimani sul tetto, dep. Siena, cardano singolo"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "1990",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "DIESEL_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "D342",
      "road_number": "D342 4003",
      "series": "ANSALDO",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/os-kar/locomotives/1017.json
{
  "manufacturer": "Os.Kar",
  "item_number": "1017",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "V",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Impresa ARMAFER livrea gialla, telaio nero, tetto marrone, 3 fanali"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2011",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "DIESEL_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "D341",
      "road_number": "",
      "series": "SECONDA SERIE",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/60132.json
{
  "manufacturer": "ACME",
  "item_number": "60132",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "IV",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva elettrica FS E646 189 nella livrea verde/grigio navetta senza modanature, finestrini, portelloni alti, fregio rosso, dep. Roma S. L."
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2009",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E646",
      "road_number": "E646 189",
      "series": "SECONDA SERIE",
      "depot": "Roma San Lorenzo",
      "livery": "verde/grigio",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "dcc_interface": "NEM_652",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/roco/locomotives/4187E-43503.json
{
  "manufacturer": "Roco",
  "item_number": "4187E/43503",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "IIa",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Nero/rosso 2a serie, con compressore meccanico"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "1982",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E626",
      "road_number": "E626 075",
      "series": "SECONDA SERIE",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/os-kar/locomotives/1689.1.json
{
  "manufacturer": "Os.Kar",
  "item_number": "1689.1",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Fanali a petrolio, respingenti moderni, vomere ripiegabile, tender a carrelli 29 mc"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": null,
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "STEAM_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "S685",
      "road_number": "S685 600",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/roco/locomotives/72893.json
{
  "manufacturer": "Roco",
  "item_number": "72893",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "IVa",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Serie 2000 Breda, vetri curvi, modanature, griglia squadrata, 2 scarichi centrali, dep. Lecco"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": null,
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "DIESEL_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "D343",
      "road_number": "D343 2001",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/60595.json
{
  "manufacturer": "ACME",
  "item_number": "60595",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "V",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva E646 081 navetta in livrea MDVC, deposito di Milano Smistamento, con vetri frontali corazzati, sfogatoi sul tetto di tipo piccolo, senza smorzatori. Nello stato del 1988"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": ""
  },
  "delivery_date": "2023/Q1",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E646",
      "road_number": "E646 081",
      "series": "SECONDA SERIE NAVETTA",
      "depot": "Milano Smistamento",
      "livery": "MDVC",
      "length_over_buffers": {
        "inches": 8.267721,
        "millimeters": 210.0
      },
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "YES"
      },
      "control": "DCC_READY",
      "dcc_interface": "MTC_21",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/60499.json
{
  "manufacturer": "ACME",
  "item_number": "60499",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "VI",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva elettrica E652 052 nella livrea XMPR2, logo FS Mercitalia Rail, vomere rosso, condotte alte"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2020",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E652",
      "road_number": "E652 052",
      "livery": "XMPR2",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "dcc_interface": "MTC_21",
      "is_dummy": false
    }
  ],
  "count": 1
}
