=== CarloMicieli/trenako/crates/tools/cli/src/schemas/catalog-items.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CatalogItem",
  "type": "object",
  "required": [
    "manufacturer",
    "item_number",
    "scale",
    "category",
    "description",
    "power_method",
    "epoch",
    "count"
  ],
  "properties": {
    "manufacturer": {
      "type": "string",
      "minLength": 3,
      "maxLength": 50
    },
    "item_number": {
      "type": "string",
      "minLength": 1,
      "maxLength": 25
    },
    "scale": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "category": {
      "type": "string",
      "enum": [
        "ELECTRIC_MULTIPLE_UNITS",
        "FREIGHT_CARS",
        "LOCOMOTIVES",
        "PASSENGER_CARS",
        "RAILCARS",
        "STARTER_SETS",
        "TRAIN_SETS"
      ]
    },
    "description": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": {
        "type": [ "string", "null" ]
      }
    },
    "power_method": {
      "type": "string",
      "enum": [
        "AC",
        "DC",
        "TRIX_EXPRESS"
      ]
    },
    "epoch": {
      "type": "string",
      "minLength": 1,
      "maxLength": 10
    },
    "delivery_date": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 4,
      "maxLength": 7
    },
    "availability_status": {
      "type": "string",
      "enum": [
        "ANNOUNCED",
        "AVAILABLE",
        "DISCONTINUED"
      ]
    },
    "rolling_stocks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RollingStock"
      }
    },
    "count": {
      "type": "integer",
      "format": "uint8",
      "minimum": 1,
      "maximum": 99
    }
  },
  "definitions": {
    "Coupling": {
      "type": "object",
      "properties": {
        "socket": {
          "type": ["string", "null"],
          "enum": [
            null,
            "NONE",
            "NEM_355",
            "NEM_356",
            "NEM_357",
            "NEM_359",
            "NEM_360",
            "NEM_362",
            "NEM_365"
          ]
        },
        "close_couplers": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "digital_shunting": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    },
    "ElectricMultipleUnitType": {
      "type": "string",
      "enum": [
        "DRIVING_CAR",
        "HIGH_SPEED_TRAIN",
        "MOTOR_CAR",
        "POWER_CAR",
        "TRAILER_CAR",
        "TRAIN_SET"
      ]
    },
    "FreightCarType": {
      "type": ["string", "null"],
      "enum": [
        null,
        "AUTO_TRANSPORT_CARS",
        "BRAKE_WAGON",
        "CONTAINER_CARS",
        "COVERED_FREIGHT_CARS",
        "DEEP_WELL_FLAT_CARS",
        "DUMP_CARS",
        "GONDOLA",
        "HEAVY_GOODS_WAGONS",
        "HINGED_COVER_WAGONS",
        "HOPPER_WAGON",
        "REFRIGERATOR_CARS",
        "SILO_CONTAINER_CARS",
        "SLIDE_TARPAULIN_WAGON",
        "SLIDING_WALL_BOXCARS",
        "SPECIAL_TRANSPORT",
        "STAKE_WAGONS",
        "SWING_ROOF_WAGON",
        "TANK_CARS",
        "TELESCOPE_HOOD_WAGONS"
      ]
    },
    "LocomotiveType": {
      "type": "string",
      "enum": [
        "DIESEL_LOCOMOTIVE",
        "ELECTRIC_LOCOMOTIVE",
        "STEAM_LOCOMOTIVE"
      ]
    },
    "PassengerCarType": {
      "type": ["string", "null"],
      "enum": [
        null,
        "BAGGAGE_CAR",
        "COMBINE_CAR",
        "COMPARTMENT_COACH",
        "DINING_CAR",
        "DOUBLE_DECKER",
        "DRIVING_TRAILER",
        "LOUNGE",
        "OBSERVATION",
        "OPEN_COACH",
        "RAILWAY_POST_OFFICE",
        "SLEEPING_CAR"
      ]
    },
    "FeatureFlag": {
      "type": "string",
      "enum": [
        "YES",
        "NO",
        "NOT_APPLICABLE"
      ]
    },
    "RailcarType": {
      "type": "string",
      "enum": [
        "null",
        "POWER_CAR",
        "TRAILER_CAR"
      ]
    },
    "RollingStock": {
      "type": "object",
      "required": [
        "category",
        "railway",
        "technical_specifications"
      ],
      "properties": {
        "category": {
          "type": "string",
          "enum": [
            "ELECTRIC_MULTIPLE_UNITS",
            "FREIGHT_CARS",
            "LOCOMOTIVES",
            "PASSENGER_CARS",
            "RAILCARS"
          ]
        },
        "control": {
          "type": ["string", "null"],
          "enum": [
            null,
            "DCC",
            "DCC_READY",
            "DCC_SOUND",
            "NO_DCC"
          ]
        },
        "dcc_interface": {
          "type": ["string", "null"],
          "enum": [
            null,
            "MTC_21",
            "NEM_651",
            "NEM_652",
            "NEM_654",
            "NEXT_18",
            "NEXT_18_S",
            "PLUX_12",
            "PLUX_16",
            "PLUX_22",
            "PLUX_8"
          ]
        },
        "depot": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100
        },
        "is_dummy": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "livery": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 50
        },
        "railway": {
          "type": "string"
        },
        "type_name": {
          "type": "string",
          "minLength": 3,
          "maxLength": 25
        },
        "road_number": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 25
        },
        "series": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 100
        },
        "service_level": {
          "type": ["string", "null"],
          "enum": [
            null,
            "FIRST_CLASS",
            "SECOND_CLASS",
            "THIRD_CLASS",
            "FIRST_AND_SECOND_CLASS",
            "FIRST_SECOND_AND_THIRD_CLASS",
            "SECOND_AND_THIRD_CLASS"
          ]
        },
        "sub_category": {
          "type": [
            "string",
            "null"
          ]
        },
        "technical_specifications": {
          "$ref": "#/definitions/TechnicalSpecifications"
        }
      }
    },
    "TechnicalSpecifications": {
      "type": "object",
      "required": [
        "body_shell",
        "chassis",
        "coupling",
        "flywheel_fitted",
        "interior_lights",
        "lights",
        "minimum_radius",
        "sprung_buffers"
      ],
      "properties": {
        "body_shell": {
          "type": ["string", "null"],
          "enum": [
            null,
            "METAL_DIE_CAST",
            "PLASTIC"
          ]
        },
        "chassis": {
          "type": ["string", "null"],
          "enum": [
            null,
            "METAL_DIE_CAST",
            "PLASTIC"
          ]
        },
        "coupling": {
          "$ref": "#/definitions/Coupling"
        },
        "flywheel_fitted": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "interior_lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "lights": {
          "$ref": "#/definitions/FeatureFlag"
        },
        "minimum_radius": {
          "type": ["number", "null"],
          "minimum": 0.1
        },
        "sprung_buffers": {
          "$ref": "#/definitions/FeatureFlag"
        }
      }
    }
  }
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/60458.json
{
  "manufacturer": "ACME",
  "item_number": "60458",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "Vb/VI",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva elettrica FS E636 117 nella livrea storica blu/grigio, vomere giallo, logo Trenitalia, pantografi 52 strisciante piano"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2018",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E636",
      "road_number": "E636 117",
      "series": "SECONDA SERIE",
      "depot": "Roma San Lorenzo",
      "livery": "blu/grigio",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "dcc_interface": "MTC_21",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/rivarossi-hornby/passenger_cars/HR4365.json
{
  "manufacturer": "Rivarossi/Hornby",
  "item_number": "HR4365",
  "scale": "H0",
  "category": "PASSENGER_CARS",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": "FS, 3-unit pack of coaches, castano livery, including 1 x luggage van Dz 83000, 1 x 1st class coach Az 13010 Type 1946 and 1 x 2nd class coach Bz33010 Type 1946, ep. III",
    "it": "FS, set di 3 carrozze Tipo 1946, composto da 1 bagagliaio Dz 83000, 1 carrozza di 1a classe Az 13010 e 1 carrozza di 2a classe Bz 33010, livrea castano, ep. III"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2024",
  "availability_status": "ANNOUNCED",
  "rolling_stocks": [
    {
      "category": "PASSENGER_CARS",
      "railway": "FS",
      "type_name": "bagagliaio Dz 83000",
      "livery": "castano",
      "length_over_buffers": {
        "inches": null,
        "millimeters": 262.0
      },
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NOT_APPLICABLE",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "NO",
        "sprung_buffers": "YES"
      },
      "is_dummy": null
    },
    {
      "category": "PASSENGER_CARS",
      "railway": "FS",
      "type_name": "Tipo 1946",
      "road_number": "Az 13010",
      "livery": "castano",
      "service_level": "FIRST_CLASS",
      "length_over_buffers": {
        "inches": null,
        "millimeters": 262.0
      },
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NOT_APPLICABLE",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "NO",
        "sprung_buffers": "YES"
      },
      "is_dummy": null
    },
    {
      "category": "PASSENGER_CARS",
      "railway": "FS",
      "type_name": "Tipo 1946",
      "road_number": "Bz 33010",
      "livery": "castano",
      "service_level": "SECOND_CLASS",
      "length_over_buffers": {
        "inches": null,
        "millimeters": 262.0
      },
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NOT_APPLICABLE",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "NO",
        "sprung_buffers": "YES"
      },
      "is_dummy": null
    }
  ],
  "count": 3
}

=== CarloMicieli/trenako/dataset/catalog_items/rivarossi/locomotives/R1438.json
{
  "manufacturer": "Rivarossi",
  "item_number": "R1438",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "V",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Livrea d'origine, 'Francia' 2 pantografi monobraccio SNCF + 1 ATR90 FS, OML Milano Sm."
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2003",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E402 B",
      "road_number": "E402 157",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/os-kar/locomotives/1687.json
{
  "manufacturer": "Os.Kar",
  "item_number": "1687",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Fanali a petrolio, tender a carrelli 22 mc con scalette standard"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2018",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "STEAM_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "685",
      "road_number": "685 443",
      "series": "SERIE 300 (ex Gr. 680)",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/lima-expert/locomotives/HL2643.json
{
  "manufacturer": "Lima Expert",
  "item_number": "HL2643",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "IVb",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Castano/isabella senza modanature, vetri Triplex, fregio castano, 12 sabbiere, dep. Udine"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2015",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E645",
      "road_number": "E645 043",
      "series": "SECONDA SERIE",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/60195.json
{
  "manufacturer": "ACME",
  "item_number": "60195",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "V",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva elettrica FS E444R 061 nella livrea di origine rosso/grigio, numeri anteriori bianchi e pantografo 52 strisciante di origine"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2022",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E444R",
      "road_number": "E444R 061",
      "depot": "Milano Centrale",
      "livery": "rosso/grigio",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_SOUND",
      "dcc_interface": "MTC_21",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/acme/locomotives/60151.json
{
  "manufacturer": "ACME",
  "item_number": "60151",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "IIIb",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "Locomotiva elettrica FS E.646 015 (1a serie) nella livrea verde e grigio di origine, fregio alato, pantografi 42 strisciante curvo, scalette piccole, dep. Napoli"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2012",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E646",
      "road_number": "E646 015",
      "series": "PRIMA SERIE",
      "depot": "Napoli Smistamento",
      "livery": "verde/grigio",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": "NEM_362",
          "close_couplers": "YES",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "dcc_interface": "NEM_652",
      "is_dummy": false
    }
  ],
  "count": 1
}

=== CarloMicieli/trenako/dataset/catalog_items/roco/locomotives/43769 (2).json
{
  "manufacturer": "Roco",
  "item_number": "43769 (2)",
  "scale": "H0",
  "category": "LOCOMOTIVES",
  "power_method": "DC",
  "epoch": "III",
  "description": {
    "de": null,
    "fr": null,
    "en": null,
    "it": "CSD Ferrovie Cecoslovacche, verde telaio nero, ex E626 2a serie, compressore meccanico"
  },
  "details": {
    "de": null,
    "fr": null,
    "en": null,
    "it": null
  },
  "delivery_date": "2001",
  "availability_status": "AVAILABLE",
  "rolling_stocks": [
    {
      "category": "LOCOMOTIVES",
      "locomotive_type": "ELECTRIC_LOCOMOTIVE",
      "railway": "FS",
      "class_name": "E626",
      "road_number": "E666 003",
      "series": "SECONDA SERIE",
      "livery": "",
      "technical_specifications": {
        "minimum_radius": 360.0,
        "coupling": {
          "socket": null,
          "close_couplers": "NO",
          "digital_shunting": "NO"
        },
        "flywheel_fitted": "NO",
        "body_shell": null,
        "chassis": null,
        "interior_lights": "NO",
        "lights": "YES",
        "sprung_buffers": "NO"
      },
      "control": "DCC_READY",
      "is_dummy": false
    }
  ],
  "count": 1
}
